version: '3'

services:
  web:
    build: .
    ports:
      - "3333:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - EXPECTED_CLIENT_HEADER=eGovStack/GOV/90000009/digitalregistries  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
